on:
  workflow_dispatch:

jobs:
  source_gem:
    name: Build+push source gem
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true

      - name: Build+push
        run: |
          rake gem gem:push
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}

  binary_gem:
    name: Build+push binary gem
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - x86_64-linux
          - aarch64-linux
          - x86_64-darwin
          - arm64-darwin

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          # For some reason, `bundler-cache: true` causes the in-Docker build
          # to crap out, so we don't use it and do it by hand instead

      - name: Build+push
        run: |
          bundle install
          rake gem:cross:${{ matrix.platform }} gem:push
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
